# Generated by Django 4.2.7 on 2023-11-29 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
