# Generated by Django 4.2.7 on 2023-11-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0002_store_latitude_store_longitude'),
        ('dp', '0003_alter_user_table'),
    ]

    operations = [
    ]
