# Generated by Django 3.1.1 on 2023-12-04 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0004_merge_20231129_1406'),
        ('dp', '0004_merge_20231204_1538'),
    ]

    operations = [
    ]
