# Generated by Django 4.2.5 on 2023-12-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0004_merge_20231129_1406'),
        ('dp', '0004_merge_20231204_1538'),
    ]

    operations = [
    ]
