# Generated by Django 4.2.5 on 2023-12-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0006_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
