# Generated by Django 4.2.7 on 2023-12-05 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0006_auto_20231204_2300'),
        ('dp', '0007_alter_user_last_login'),
    ]

    operations = [
    ]
