# Generated by Django 4.2.7 on 2023-11-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=400)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('is_cafe', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dp/store_images/%Y/%m/%d')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
