# Generated by Django 4.2.7 on 2023-11-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='store',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
